from .FitNet import HintLoss
from .AT import Attention
from .KD import DistillKL
from .SP import Similarity
from .VID import VIDLoss
from .SemCKD import SemCKDLoss
from .icl import IclLoss
from .dml import DML
from .ab import AB
from .cc import CC
from .pkt import PKTCosSim
from .nst import NST
from .rkd import RKD